
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      firstName: "Hamish"
      lastName: "Sams"
      gitHub: "Hammie217"
      linkedin: "hamish-sams-2ba767153"
      twitter: "Hammie217"
      facebook: "Hammie217"

sass:
    style: compressed
